version: 0.2
env:
  parameter-store:
    PASSWORD: Solutions

phases:
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the dist folder
      - echo $PASSWORD

  post_build:
    commands:
      - echo Build completed on `date`
      - printenv > .env
      - cat .env
      - touch .env.example
# Include only the files required for your application to run.
artifacts:
  files:
    - index.js
    - public/**/*
    - app.json
    - node_modules/**/*
    - package.json
    - Procfile
    - appspec.yml
    - '**/*'

     
