
name: Build & deploy
    
on:
  push:
    branches:
      - master
            
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
  
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
             aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
             aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
             aws-region: ap-south-1
            
      - name: Running linux command
        run: |
         ls -lha 
  
      - name: Deploy to S3 bucket
        run: aws s3 sync ./ s3://my0sample  
         
